# Generated by Django 4.2.30 on 2026-04-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRecord',
            fields=[
                ('lease_id', models.AutoField(db_column='LeaseID', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('security_deposit', models.DecimalField(db_column='SecurityDep', decimal_places=2, max_digits=7)),
                ('monthly_rent', models.DecimalField(db_column='MonthlyRent', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'LEASE_RECORD',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(db_column='PropertyID', primary_key=True, serialize=False)),
                ('province', models.CharField(db_column='Province', max_length=50)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('street_name', models.CharField(db_column='StName', max_length=100)),
                ('post_code', models.CharField(db_column='PostCode', max_length=20)),
                ('suite', models.CharField(blank=True, db_column='Suite', max_length=20, null=True)),
                ('apartment', models.CharField(db_column='Appart', max_length=20)),
                ('is_rented', models.BooleanField(db_column='IsRented', default=False)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'PROPERTY',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FName', max_length=50)),
                ('last_name', models.CharField(db_column='LName', max_length=50)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('user_type', models.CharField(choices=[('ProspectiveRenter', 'Prospective Renter'), ('Tenant', 'Tenant'), ('PropertyManager', 'Property Manager')], db_column='UserType', max_length=20)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaytID', primary_key=True, serialize=False)),
                ('pay_date', models.DateField(db_column='PayDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=7)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'Credit Card'), ('DebitCard', 'Debit Card'), ('Transfer', 'Transfer')], db_column='Method', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_column='Status', default='Pending', max_length=10)),
                ('lease', models.ForeignKey(db_column='LeaseID', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental_app.leaserecord')),
            ],
            options={
                'db_table': 'RENT_PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('listing_id', models.AutoField(db_column='ListingID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=7)),
                ('description', models.TextField(db_column='Description')),
                ('date_posted', models.DateField(db_column='DatePosted')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Rented', 'Rented'), ('Closed', 'Closed')], db_column='Status', default='Active', max_length=10)),
                ('property', models.ForeignKey(db_column='PropertyID', on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to='rental_app.property')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to='rental_app.user')),
            ],
            options={
                'db_table': 'RENTAL_LISTING',
            },
        ),
        migrations.CreateModel(
            name='ManagementRequest',
            fields=[
                ('request_id', models.AutoField(db_column='RequestID', primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(db_column='DateSubm')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], db_column='Status', default='Pending', max_length=10)),
                ('permission', models.CharField(choices=[('Granted', 'Granted'), ('Denied', 'Denied'), ('Pending', 'Pending')], db_column='Permission', default='Pending', max_length=10)),
                ('description', models.TextField(db_column='Description')),
                ('property', models.ForeignKey(db_column='PropertyID', on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to='rental_app.property')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to='rental_app.user')),
            ],
            options={
                'db_table': 'MANAGEMENT_REQUEST',
            },
        ),
        migrations.AddField(
            model_name='leaserecord',
            name='property',
            field=models.ForeignKey(db_column='PropertyID', on_delete=django.db.models.deletion.CASCADE, related_name='lease_records', to='rental_app.property'),
        ),
        migrations.AddField(
            model_name='leaserecord',
            name='user',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='lease_records', to='rental_app.user'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(db_column='AppointID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], db_column='Status', default='Pending', max_length=10)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='rental_app.user')),
            ],
            options={
                'db_table': 'APPOINTMENT',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_num', models.IntegerField(db_column='SlotNum')),
                ('day', models.IntegerField(db_column='Day')),
                ('month', models.IntegerField(db_column='Month')),
                ('year', models.IntegerField(db_column='Year')),
                ('appointment', models.ForeignKey(db_column='AppointID', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='rental_app.appointment')),
            ],
            options={
                'db_table': 'TIME_SLOT',
                'unique_together': {('appointment', 'slot_num')},
            },
        ),
    ]
