# Generated by Django 4.2.30 on 2026-04-15 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='ManagerID', limit_choices_to={'user_type': 'PropertyManager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_properties', to='rental_app.user'),
        ),
    ]
