# Generated by Django 4.2.30 on 2026-04-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_timeslot_hour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('street_name', 'city', 'province', 'post_code', 'suite', 'apartment')},
        ),
    ]
